### ISSUE TITLE
Generating only Rmd files for Solution and Assignments

### ISSUE THREAD

**Issue by sukhjitsehra** [coatless/assignr#9]
Hi, 

I want to generate only the Rmd files for Solution and Assignments without html, pdf and tex version. 

Any parameter value that can help to generate the desired results.

Thanks

**Comment by coatless** [comment]
@sukhjitsehra not yet. 

Can you provide more details about why you want to avoid rendering output files?

**Comment by sukhjitsehra** [comment]
Thanks @coatless 

As I provide RMD files to students, so I wanted to know if any option/parameter can create only RMD files for assign and soon.

**Comment by coatless** [comment]
@sukhjitsehra implemented a boolean flag in #10 

Can you give it a go by using:

```r
if(!requireNamespace('remotes')) install.packages('remotes')

remotes::install_github('r-assist/assignr@render-flag')
```

Then:

```r
library("assignr")

hw00_file = get_example_filepath("hw00-main.Rmd")
assignr(hw00_file, "test", render_files = FALSE)
```

**Comment by sukhjitsehra** [comment]
@coatless 
I encountered the following error.
> remotes::install_github('r-assist/assignr@render-flag')
Downloading GitHub repo r-assist/assignr@render-flag
Error in utils::download.file(url, path, method = method, quiet = quiet,  : 
  cannot open URL 'https://api.github.com/repos/r-assist/assignr/tarball/render-flag'

**Comment by coatless** [comment]
@sukhjitsehra it was merged into the master. Feel free to download it with: 

```r
if(!requireNamespace('remotes')) install.packages('remotes')

remotes::install_github('r-assist/assignr')
```

**Comment by sukhjitsehra** [comment]
Great thanks It worked
